services:
  - type: worker
    name: session-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        value: "23669137"
        sync: true

      - key: API_HASH
        value: "383fc7aed5eb613e791a8d792c17f22a"
        sync: true

      - key: BOT_TOKEN
        value: "8557732228:AAEv9cKmLFiN4UJgMr_oVFI4kHT937u26DQ"
        sync: true

      - key: MONGODB_URI
        value: "mongodb+srv://AhmedMidoo:AhmedMidoo@ahmedmidoo.ubr4b0r.mongodb.net/?appName=AhmedMidoo"
        sync: true
